version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20
    
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20
